Repository red-hat-data-services/kubeflow, pull requests merged in 2024-10, with the labels that each got.

#117 sync master branch with opendatahub release branch v1.9-branch
  .github/workflows/sync-branches-through-py.yaml
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/base/params.env
Labels: lgtm, approved

#118 Review Dockerfile and RPM files for building odh-kf-notebook-controller and odh-notebook-controller in Konflux
  components/notebook-controller/Dockerfile.konflux
  components/notebook-controller/rpms.in.yaml
  components/notebook-controller/rpms.lock.yaml
  components/notebook-controller/ubi.repo
  components/odh-notebook-controller/Dockerfile.konflux
  components/odh-notebook-controller/rpms.in.yaml
  components/odh-notebook-controller/rpms.lock.yaml
  components/odh-notebook-controller/ubi.repo
Labels: lgtm, approved, tide/merge-method-squash

#120 Revert "[v1.9-branch] RHOAIENG-10827: feat(nbcs): update ose-oauth-pr…
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/controllers/notebook_oauth.go
Labels: lgtm

#119 update LABELs and remove unwanted ARGs for konflux builds
  components/notebook-controller/Dockerfile.konflux
  components/odh-notebook-controller/Dockerfile.konflux
Labels: lgtm

#125 Sync master from odh v1.9-branch to get the latest changes ready for rhoai-nightly
  .github/workflows/notebook_controller_integration_test.yaml
  .github/workflows/odh_notebook_controller_integration_test.yaml
  .github/workflows/sync-branches-through-pr.yaml
  components/notebook-controller/Makefile
  components/notebook-controller/api/v1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/notebook-controller/api/v1beta1/zz_generated.deepcopy.go
  components/notebook-controller/config/crd/bases/kubeflow.org_notebooks.yaml
  components/notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/manager/manager.yaml
  components/odh-notebook-controller/config/rbac/role.yaml
  components/odh-notebook-controller/config/webhook/manifests.yaml
  components/odh-notebook-controller/controllers/notebook_oauth.go
Labels: lgtm, approved

#128 Merge branch `v1.9-branch` of github.com:opendatahub-io/kubeflow into sync-ds
  components/notebook-controller/config/overlays/openshift/params.env
  components/odh-notebook-controller/Makefile
  components/odh-notebook-controller/config/base/params.env
  components/odh-notebook-controller/controllers/notebook_controller.go
Labels: lgtm, approved

#132 update Dockerfile.konflux
  components/notebook-controller/Dockerfile.konflux
  components/odh-notebook-controller/Dockerfile.konflux
Labels: lgtm, ok-to-test

#140 RHOAIENG-14150: sync Dockerfiles from CPaaS repo so we get clean CI checks
  components/notebook-controller/Dockerfile
  components/odh-notebook-controller/Dockerfile
Labels: lgtm, approved

#139 RHOAIENG-14150: rename `helper.go` to fix govulncheck failure
  components/odh-notebook-controller/e2e/helper_test.go
Labels: lgtm, approved

#138 RHOAIENG-14150: add GitHub actions workflow files from opendatahub-io/kubeflow main branch
  .github/workflows/code-quality.yaml
  .github/workflows/notebook_controller_integration_test.yaml
  .github/workflows/notebook_controller_unit_test.yaml
  .github/workflows/odh_notebook_controller_integration_test.yaml
  .github/workflows/odh_notebook_controller_unit_test.yaml
  components/notebook-controller/Dockerfile
  components/odh-notebook-controller/Dockerfile
Labels: lgtm, approved

#121 NO-JIRA: fix(gha): replace `oc` with `kubectl` in notebook_controller_integration_test.yaml
  .github/workflows/notebook_controller_integration_test.yaml
  .github/workflows/odh_notebook_controller_integration_test.yaml
Labels: lgtm, approved

#143 update dockerfile for adding required LABEL
  components/notebook-controller/Dockerfile.konflux
  components/odh-notebook-controller/Dockerfile.konflux
Labels: lgtm, approved
